# Default config file

# File path for the OUI database file
# db_path = "/home/user1/ouioui/data/oui.db"

# Custom OUI
# Array of arrays ["AA:BB:CC", "Example Manuf"]
#
# custom_oui = [
#  ["AA:BB:CC", "Example Manuf"],
#  ["DD:EE:FF", "Example Manuf 2"]
# ]